CREATE
USER 'tiankafei'@'%' IDENTIFIED BY 'tiankafei';

GRANT GRANT
OPTION ON *.* TO 'tiankafei'@'%';

GRANT
SELECT,
INSERT
,
UPDATE,
DELETE, CREATE, DROP, RELOAD, SHUTDOWN, PROCESS, FILE, REFERENCES, INDEX, ALTER, SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER
ON *.* TO 'tiankafei'@'%';



CREATE
USER 'redmine'@'%' IDENTIFIED BY 'redmine';

GRANT GRANT
OPTION ON *.* TO 'redmine'@'%';

GRANT
SELECT,
INSERT
,
UPDATE,
DELETE, CREATE, DROP, RELOAD, SHUTDOWN, PROCESS, FILE, REFERENCES, INDEX, ALTER, SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER
ON *.* TO 'redmine'@'%';