purge recyclebin;
SELECT * from tab t;

SELECT * from TKF_BUSINESS_DATA;
SELECT * from TKF_LOGIN_USER;
SELECT * from TKF_ROLE_BUSINESS_DATA;
SELECT * from TKF_ROLE_DATA;
SELECT * from TKF_SYS_CATALOG;
SELECT * from TKF_SYS_TABLE;
SELECT * from TKF_SYS_COLUMN;
SELECT * from TKF_SYS_LOG;
SELECT * from TKF_SYS_MESSAGE;
SELECT * from TKF_SYS_OPERATE_TIME;
SELECT * from TKF_SYS_PARAM;
SELECT * from TKF_USER_DATA;
SELECT * from TKF_USER_ROLE_DATA;

